### ISSUE TITLE
Failed to HW transcode HDR/DV using Nvidia NVENC 

### ISSUE THREAD

**Issue by alyx404** [jellyfin/jellyfin-ffmpeg#180]
ffmpeg says "Unable to load library 'nvptxJitCompiler.dll'"
There's "nvptxJitCompiler32.dll" (and 64) in Windows dll library.
Reinstall both Game Ready and Studio latest driver doesn't work.

**Steps To Reproduce**
1. Using jellyfin-ffmpeg blobs
2. Play any transcode needed file
3. Failed

**Expected Behavior**
Transcode successfully

**System (please complete the following information):**

- **Platform:**: x64 Windows
- **Operating System:** Windows Server 2022
- **Virtualization:** None
- **Jellyfin Version:** 10.8.4
- **Jellyfin-FFmpeg Version:** 5.1-2
- **Hardware Acceleration:** NVENC
- **CPU & GPU Model:** E3-1260V3 - GTX1050 2G

**FFmpeg Logs**
logs below:
gyan.dev version
5.1-1 that comes with 10.8.4
5.1-2 downloaded from action

**Comment by alyx404** [comment]
[FFmpeg.Transcode_latest_action.log](https://github.com/jellyfin/jellyfin-ffmpeg/files/9372826/FFmpeg.Transcode_latest_action.log)
[FFmpeg.Transcode_stock.log](https://github.com/jellyfin/jellyfin-ffmpeg/files/9372827/FFmpeg.Transcode_stock.log)
[FFmpeg.Transcode_gyan.dev_version.log](https://github.com/jellyfin/jellyfin-ffmpeg/files/9372828/FFmpeg.Transcode_gyan.dev_version.log)

**Comment by nyanmisaka** [comment]
I'm sure that this is a driver or upstream issue. You can also reproduce this if you try any cuda filter with the ffmpeg from gyan.dev or BtbN.

`nvptxJitCompiler.dll` is the JIT compiler used in cuda filters, which is missing or not well installed on your system due to the incompatible driver system combination.


```
Version: 516.94  WHQL
Release Date: 2022.8.9
Operating System: Windows 10 64-bit, Windows 11
```
AFAIK Nvidia's game ready driver and studio driver are only designed for standard Windows 10 and 11 instead of Windows server. Switch back to Windows 10 or 11 should fix this issue.

**Comment by alyx404** [comment]
Alright i got other tech guys' replies as well. NVIDIA Driver didnt install compoments completely because of serverOS and headless.
Tried AMD GPU (with "consumer" Driver) and no any issue. Thanks NVIDIA!
Switching back to Windows 10 and plug a dummy should fix.
