### ISSUE TITLE
Please do not install binaries into DATADIR

### ISSUE THREAD

**Issue by CameronNemo** [jellyfin/jellyfin-ffmpeg#2]
https://github.com/jellyfin/jellyfin-ffmpeg/blob/a0944d9cb8a8ea89422fab90719dc78e3662c802/Makefile#L126

Please use libexecdir for these files. DATADIR has this description in the GNU documentation:

>The directory for installing idiosyncratic read-only **architecture-independent** data files for this program

https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

**Comment by joshuaboniface** [comment]
OK, so these *should* go in `/usr/lib/jellyfin-ffmpeg`. I'm cool with that.

Note that I've tried to avoid editing the default Makefile which comes right from upstream. I set the location in https://github.com/jellyfin/jellyfin-ffmpeg/blob/jellyfin/debian/jellyfin-ffmpeg.install directly.

**Comment by joshuaboniface** [comment]
I found nothing in the Debian policy manual that explicitly defined what should or shouldn't go in `/usr/share` when I first set this up, but I have finally found a reference that suggests libexecdir is `/usr/lib` by default. (https://www.debian.org/doc/manuals/maint-guide/advanced.en.html#idm4181)

Now, that said - changing this is going to be an absolute pain. If we change the install location and someone updates this package but not their Jellyfin configs (or vice-versa on a release), things are going to break for a lot of people who probably don't care too much about the distinction between `/usr/share` and `/usr/lib`. It's going to be a huge amount of work, both for me and potentially for some users, for seemingly no benefit aside from the tingles of compliance with the GNU standards. 

If you can provide a very compelling reason for the location change aside from the GNU manual, I'll consider putting in the effort for 10.3.0 (due to start RC testing in the next couple days at the latest). But I just have a hard time seeing the value.

**Comment by CameronNemo** [comment]
It will be harder to make the switch at a later point in time. People generally do not expect architecture dependent code in /usr/share. Not putting the binaries in libexecdir (/usr/lib on Debian based systems) may break multilib setups. Debian policy may prohibit the practice in the future, which could make it harder to get jellyfin into Debian.

**Comment by joshuaboniface** [comment]
"Strong opinions, loosely held" as they say. Multilib is something I still see around in the wild and I think is valid. We're not aiming for inclusion into Debian any time soon (due to the dependency on .NET), but that said it is more future-looking. You've convinced me.

**Comment by CameronNemo** [comment]
Thank you!

**Comment by joshuaboniface** [comment]
I added some transitional symlinks in the `postinst` and `prerm` scripts as well to avoid the impact this may have on RC testing, since I don't want to release the updated `.deb` packages until 10.3.0 drops. They will be removed in a subsequent version once things stabilize.
