### ISSUE TITLE
Update to ffmpeg 6.1

### ISSUE THREAD

**Issue by arthsmn** [jellyfin/jellyfin-ffmpeg#306]
I would like to request the update of this to the newer ffmpeg 6.1. This brings a lot of improvements (as it can be seen here: https://ffmpeg.org/index.html#news), but also it enables more up-to-date versions of libraries such as nv-codec-headers and libplacebo. I'm a NixOS package maintainer and we're having issues with package updates because some packages require newer versions of these libraries, but this package doesn't compile (as it can be seen here: https://github.com/NixOS/nixpkgs/pull/260538). As ffmpeg is a vital dependency I think this update is worth and needed.

**Comment by nyanmisaka** [comment]
@arthsmn 

Thank you for your mail! I investigated and found that it was due to the deletion of some [deprecated definitions in nv-codec-headers 12.1](https://github.com/FFmpeg/nv-codec-headers/commit/58ab60e03a707f529f298d4ea49e79a30508b193), and FFmpeg 6.0 relied on them for compile-time checking. The good news is that the [FFmpeg 6.0.1 hotfix has fixed this problem](https://github.com/FFmpeg/FFmpeg/commit/9212b53ed5b2f7346036936d500e7954190fb08b), and I will release jellyfin-ffmpeg 6.0.1-1 as soon as possible to solve this.

Btw FFmpeg 6.1 has made drastic changes to the Vulkan framework, which will cause Vulkan filters to not work properly on old graphics cards and old drivers. Therefore we decided to postpone the update to 6.1 and wait to see FFmpeg 7.0 early next year.

**Comment by arthsmn** [comment]
Hey, thanks a lot for the information! I was trying to figure out these things but ffmpeg is really hard to understand for the first time. I will keep track of the repository. Thanks to your work on jellyfin and open-source, I love your project!

**Comment by arthsmn** [comment]
Closing this in favor of waiting for ffmpeg 7.0 next year.
