### ISSUE TITLE
Corrupted decode when starting in the middle of a H.264 High 4:4:4 Predictive@L5 file

### ISSUE THREAD

**Issue by timo95** [jellyfin/jellyfin-ffmpeg#47]
**Describe the bug**

Starting a decode in the middle of a H.264 High 4:4:4 Predictive@L5 file sometimes corrupts (depends on the starting position, not random). Playing the file from the beginning works without problem! Only skipping triggers it. I have no files with other settings to test.

I added an image below, and mediainfo for one of the files: [mediainfo.txt](https://github.com/jellyfin/jellyfin-ffmpeg/files/4933247/mediainfo.txt)

Could **not** reproduce with:
- Infuse 6's software decoder on iOS.
- MPC-HC using K-Lite Codec Pack on Windows 10.
- VLC 3.0.11 on Windows 10
- MPV 0.32.0 on Windows 10

**System:**
 - OS: OMV 4 (Debian 9)
 - Jellyfin Version: 10.5.5

**To Reproduce**

Screen Grabber:
1. Deactivate all episode image sources but Screen Grabber for library
2. Add High 4:4:4 Predictive@L5 file to library
3. Some High 4:4:4 Predictive@L5 files will have a corrupted episode image

Transcoding:
1. Add High 4:4:4 Predictive@L5 file to library
2. Play using transcoding
3. Jump a few times to unbuffered spots until decode corrupts

**Expected behavior**

It works.

**Screenshots**

Episode image (playback has similar artefacts):
![grafik](https://user-images.githubusercontent.com/24251362/87701540-729bf000-c798-11ea-8f08-0be6f1163e2d.png)

**Comment by nyanmisaka** [comment]
I have also encountered similar issues on this relatively rare format.
It looks like an internal bug of ffmpeg or we need to add additional unknown cli options.

**Comment by nyanmisaka** [comment]
This issue is caused by encoding H264 High 4:4:4 using old libx264 version(<151) with stripped `x264_build` info.
To fix this video, you can follow these steps without re-encoding the video.

1. Extract the raw h264 data.
`ffmpeg -i "Z:\Anime\Fatekaleid liner Prisma☆Illya 3rei!!\eXmendiC [eX]\Special\Fatekaleid liner Prisma☆Illya 3rei!! NCED1 ger sub.mkv" -c:v copy -an -sn -y "raw.h264"`

2. Insert the missing `x264_build` info into video stream.
`ffmpeg -i "raw.h264" -i "Z:\Anime\Fatekaleid liner Prisma☆Illya 3rei!!\eXmendiC [eX]\Special\Fatekaleid liner Prisma☆Illya 3rei!! NCED1 ger sub.mkv" -map 0:v -c:v copy -bsf:v h264_metadata="sei_user_data=dc45e9bde6d948b7962cd820d923eeef+x264 - core 148 r2721+55 e19946b t_mod_Custom [10-bit@all X86_64]" -an -sn -v quiet -y "videostream.mp4"`

3. Restore audio and subtitle streams into mkv container.
`ffmpeg -i "videostream.mp4" -i "Z:\Anime\Fatekaleid liner Prisma☆Illya 3rei!!\eXmendiC [eX]\Special\Fatekaleid liner Prisma☆Illya 3rei!! NCED1 ger sub.mkv" -map 0:v -map 1:a -map 1:s -c:v copy -c:a copy -c:s copy -v quiet -y "Fatekaleid liner Prisma☆Illya 3rei!! NCED1 ger sub fixed.mp4"`

For more details:
- https://trac.ffmpeg.org/ticket/6717
- https://patchwork.ffmpeg.org/project/ffmpeg/patch/1497556233-65009-1-git-send-email-rsbultje@gmail.com/
- https://patchwork.ffmpeg.org/project/ffmpeg/patch/CAB0OVGpQdn1G8=VNju6_WbMw65gLc3VOApK=5gKP9BgCN0=9Hw@mail.gmail.com/
- https://github.com/mpv-player/mpv/commit/5e50fe30492cd593ba33d3daa846b650c7d302ca
- https://superuser.com/questions/1302276/properly-fix-videos-which-were-encoded-with-old-version-of-x264
