### ISSUE TITLE
Include .pc file in .deb packages

### ISSUE THREAD

**Issue by linzuzeng** [jellyfin/jellyfin-ffmpeg#497]
This would allow third party program to build with the compiled .so files with jellyfin-ffmpeg

**Comment by nyanmisaka** [comment]
`jellyfin-ffmpeg` is designed to be used only inside Jellyfin Server. And because it is a fork that contains some hacks, we cannot keep its API/ABI stable like upstream FFmpeg, which is fatal to use it through `pkg-config`. So we have no plans to do this, at least not yet.

If you need the features from `jellyfin-ffmpeg`, please build your own fork of FFmpeg and ship it with your project.
